# ---------------------------------------------------------------
# Seed data generated by AI
# ---------------------------------------------------------------
 
AUTHORS = [
    {"openlibrary_key": "/authors/OL26320A",  "name": "J.R.R. Tolkien"},
    {"openlibrary_key": "/authors/OL18319A",  "name": "Ursula K. Le Guin"},
    {"openlibrary_key": "/authors/OL22098A",  "name": "Frank Herbert"},
    {"openlibrary_key": "/authors/OL23919A",  "name": "Isaac Asimov"},
    {"openlibrary_key": "/authors/OL24964A",  "name": "Philip K. Dick"},
]
 
# Each book entry includes an 'authors' list of openlibrary_keys
# so we can resolve the Author objects after creating them.
BOOKS = [
    {"openlibrary_key": "/works/OL27516W",    "title": "The Lord of the Rings",       "authors": ["/authors/OL26320A"]},
    {"openlibrary_key": "/works/OL27516X",    "title": "The Hobbit",                  "authors": ["/authors/OL26320A"]},
    {"openlibrary_key": "/works/OL27516Y",    "title": "The Silmarillion",             "authors": ["/authors/OL26320A"]},
    {"openlibrary_key": "/works/OL14933414W", "title": "A Wizard of Earthsea",         "authors": ["/authors/OL18319A"]},
    {"openlibrary_key": "/works/OL14933415W", "title": "The Left Hand of Darkness",    "authors": ["/authors/OL18319A"]},
    {"openlibrary_key": "/works/OL14933416W", "title": "The Dispossessed",             "authors": ["/authors/OL18319A"]},
    {"openlibrary_key": "/works/OL102574W",   "title": "Dune",                         "authors": ["/authors/OL22098A"]},
    {"openlibrary_key": "/works/OL102575W",   "title": "Dune Messiah",                 "authors": ["/authors/OL22098A"]},
    {"openlibrary_key": "/works/OL46404W",    "title": "Foundation",                   "authors": ["/authors/OL23919A"]},
    {"openlibrary_key": "/works/OL46405W",    "title": "The Caves of Steel",           "authors": ["/authors/OL23919A"]},
    {"openlibrary_key": "/works/OL2172W",     "title": "Do Androids Dream of Electric Sheep?", "authors": ["/authors/OL24964A"]},
    {"openlibrary_key": "/works/OL2173W",     "title": "The Man in the High Castle",   "authors": ["/authors/OL24964A"]},
]
 
# Each user entry defines which books they have rated and at what score.
# Books are referenced by their openlibrary_key for readability.
# Users with overlapping high ratings will surface as reading buddies.
USERS = [
    {
        "username": "alice",
        "ratings": {
            "/works/OL27516W":    5,  # LotR
            "/works/OL27516X":    5,  # Hobbit
            "/works/OL14933414W": 4,  # Earthsea
            "/works/OL102574W":   5,  # Dune
        },
    },
    {
        "username": "bob",
        "ratings": {
            "/works/OL27516W":    5,  # LotR
            "/works/OL27516X":    4,  # Hobbit
            "/works/OL27516Y":    5,  # Silmarillion
            "/works/OL14933414W": 5,  # Earthsea
            "/works/OL14933415W": 4,  # Left Hand of Darkness
        },
    },
    {
        "username": "carol",
        "ratings": {
            "/works/OL102574W":   5,  # Dune
            "/works/OL102575W":   5,  # Dune Messiah
            "/works/OL46404W":    4,  # Foundation
            "/works/OL27516W":    4,  # LotR
        },
    },
    {
        "username": "dave",
        "ratings": {
            "/works/OL46404W":    5,  # Foundation
            "/works/OL46405W":    5,  # Caves of Steel
            "/works/OL2172W":     4,  # Do Androids Dream
            "/works/OL102574W":   4,  # Dune
        },
    },
    {
        "username": "eve",
        "ratings": {
            "/works/OL14933414W": 5,  # Earthsea
            "/works/OL14933415W": 5,  # Left Hand of Darkness
            "/works/OL14933416W": 5,  # Dispossessed
            "/works/OL27516W":    3,  # LotR (weak signal)
        },
    },
    {
        "username": "frank",
        "ratings": {
            "/works/OL2172W":     5,  # Do Androids Dream
            "/works/OL2173W":     5,  # Man in the High Castle
            "/works/OL46404W":    4,  # Foundation
            "/works/OL46405W":    3,  # Caves of Steel (weak signal)
        },
    },
    {
        "username": "grace",
        "ratings": {
            "/works/OL102574W":   5,  # Dune
            "/works/OL102575W":   4,  # Dune Messiah
            "/works/OL2172W":     5,  # Do Androids Dream
            "/works/OL14933416W": 4,  # Dispossessed
        },
    },
    {
        "username": "henry",
        "ratings": {
            "/works/OL27516W":    4,  # LotR
            "/works/OL46404W":    5,  # Foundation
            "/works/OL102574W":   5,  # Dune
            "/works/OL2173W":     4,  # Man in the High Castle
        },
    },
    {
        "username": "iris",
        "ratings": {
            "/works/OL14933415W": 5,  # Left Hand of Darkness
            "/works/OL14933416W": 5,  # Dispossessed
            "/works/OL2172W":     4,  # Do Androids Dream
            "/works/OL46405W":    4,  # Caves of Steel
        },
    },
    {
        "username": "jack",
        "ratings": {
            "/works/OL27516Y":    5,  # Silmarillion
            "/works/OL27516X":    5,  # Hobbit
            "/works/OL102574W":   4,  # Dune
            "/works/OL46404W":    4,  # Foundation
        },
    },
]