"""
Django settings for luckyreads project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import sys
import sentry_sdk
from celery.schedules import crontab


def environ_bool(key: str, default=0):
    return bool(int(os.environ.get(key, default)))



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-changeme")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = environ_bool("DJANGO_DEBUG", 0)
"""Debug mode implements better logging."""

DEV = os.environ.get("DEV", None) == "true"
"""Dev mode installs additional development packages."""

TESTING = sys.argv[1:2] == ["test"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "django_celery_beat",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "drf_standardized_errors",
    "django_filters",
    'channels',
    
    'apps.core',

    'apps.users',
    'apps.books',
    'apps.recommendations',
    'apps.messaging',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'luckyreads.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'luckyreads.wsgi.application'

sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN", ""), send_default_pii=True, traces_sample_rate=1.0
)


##########################################
# == Static Files Config =============== #
##########################################
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
S3_STORAGE_BACKEND = environ_bool("S3_STORAGE_BACKEND", 1) and not TESTING
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# URL path to file
STATIC_URL = "/files/static/"
MEDIA_URL = "/files/media/public/"

# Physical location in file system
MEDIA_ROOT = "/vol/web/media/public"
STATIC_ROOT = "/vol/web/static"

# Media and static storage config
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {},
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        "OPTIONS": {},
    },
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



#######################
# == Cache Config === #
#######################

REDIS_HOST = os.environ.get("REDIS_HOST", "redis")
DJANGO_CACHE_REDIS_DB = os.environ.get("DJANGO_CACHE_REDIS_DB", 0)

DJANGO_REDIS_URL = f"redis://{REDIS_HOST}/{DJANGO_CACHE_REDIS_DB}"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": DJANGO_REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

#######################
# == Celery Config == #
#######################
DJANGO_ENABLE_CELERY = environ_bool("DJANGO_ENABLE_CELERY", 1)
"""When disabled, runs as a single server."""

# What celery uses to communicate to workers
CELERY_BROKER_REDIS_DB = os.environ.get("CELERY_BROKER_REDIS_DB", 1)
CELERY_BROKER_URL = f"redis://{REDIS_HOST}/{CELERY_BROKER_REDIS_DB}"

# What celery uses to store results of tasks
CELERY_RESULT_BACKEND_REDIS_DB = os.environ.get("CELERY_RESULT_BROKER_REDIS_DB", 1)
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}/{CELERY_RESULT_BACKEND_REDIS_DB}"

CELERY_TASK_ACKS_LATE = bool(int(os.environ.get("CELERY_TASK_ACKS_LATE", "1")))
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = bool(
    int(os.environ.get("CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP", "1"))
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Custom schedules
CELERY_BEAT_SCHEDULE = {}
CELERY_BEAT_ENABLE_HEARTBEAT = environ_bool("CELERY_BEAT_ENABLE_HEARTBEAT", 0)

if CELERY_BEAT_ENABLE_HEARTBEAT:
    CELERY_BEAT_SCHEDULE["heartbeat"] = {
        "task": "core.tasks.heartbeat_task",
        "schedule": crontab(minute="*"),
    }

#########################
# == Channels Config == #
#########################
CHANNELS_REDIS_DB = os.environ.get("CHANNELS_REDIS_DB", 2)
CHANNELS_REDIS_URL = f"redis://{REDIS_HOST}/{CHANNELS_REDIS_DB}"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [CHANNELS_REDIS_URL],
        },
    },
}