# Generated by Django 5.2.12 on 2026-03-31 06:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=64, null=True, unique=True
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=64, unique=True)),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="password"
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("bio", models.TextField(blank=True, default="")),
                ("avatar_url", models.URLField(blank=True, default="")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="auth.permission"
                    ),
                ),
            ],
            options={
                "db_table": "users_user",
            },
        ),
    ]
