# Generated by Django 5.2.12 on 2026-04-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="bio",
        ),
    ]
