# Generated by Django 5.2.12 on 2026-04-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_review_rating"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="rating_between_1_and_5",
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="rating_between_1_and_5",
                violation_error_message="Rating must be between 1 and 5",
            ),
        ),
    ]
